/**
 * Excalidraw scene, CSV and Markdown exports of a resolved selection.
 * Colours here are hex on purpose: the file is opened outside the site.
 */
import { computeLayout, NODE_H } from './layout'
import type { Direction, Product, Resolved } from './netCatalog'
import { nodeById } from './netCatalog'

export interface ExportLabels {
  title: string
  generatedBy: string          // "Generated by Machine Identity Academy (demo.minha.cloud)"
  selected: string             // "Selected"
  edition: string              // "Edition"
  editionValue: string         // "SaaS" | "Self-Hosted"
  legend: string
  outbound: string
  inbound: string
  internal: string
  external: string
  inferredNote: string         // footnote on inferred flows
}

export const DEFAULT_EXPORT_LABELS: ExportLabels = {
  title: 'Reference architecture',
  generatedBy: 'Generated by Machine Identity Academy (demo.minha.cloud)',
  selected: 'Selected',
  edition: 'Edition',
  editionValue: 'SaaS',
  legend: 'Legend',
  outbound: 'Outbound from customer network',
  inbound: 'Inbound to customer network',
  internal: 'Internal (customer network)',
  external: 'Provider to provider (no customer rule)',
  inferredNote: 'Flows marked "inferred" follow the docs but the port or endpoint is not spelled out there: confirm before opening firewall rules.',
}

export const PRODUCT_COLORS: Record<Product, { stroke: string; bg: string }> = {
  sm: { stroke: '#1d4ed8', bg: '#dbeafe' },
  swa: { stroke: '#0e7490', bg: '#cffafe' },
  cp: { stroke: '#6d28d9', bg: '#ede9fe' },
  shub: { stroke: '#a21caf', bg: '#fae8ff' },
  customer: { stroke: '#475569', bg: '#f1f5f9' },
  external: { stroke: '#334155', bg: '#ffffff' },
}

export const DIRECTION_STYLE: Record<Direction, { stroke: string; style: 'solid' | 'dashed' | 'dotted' }> = {
  outbound: { stroke: '#1d4ed8', style: 'solid' },
  inbound: { stroke: '#dc2626', style: 'solid' },
  internal: { stroke: '#475569', style: 'dashed' },
  external: { stroke: '#94a3b8', style: 'dotted' },
}

// ---------------------------------------------------------------------------
// Excalidraw element helpers
// ---------------------------------------------------------------------------

type El = Record<string, unknown>

function hash(s: string): number {
  let h = 2166136261
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619) }
  return Math.abs(h) % 2147483647
}

const NOW = 1790000000000

function base(id: string, type: string, x: number, y: number, w: number, h: number, extra: El = {}): El {
  return {
    id, type, x, y, width: w, height: h, angle: 0,
    strokeColor: '#1e293b', backgroundColor: 'transparent', fillStyle: 'solid',
    strokeWidth: 1, strokeStyle: 'solid', roughness: 0, opacity: 100,
    groupIds: [], frameId: null, roundness: null,
    seed: hash(id), version: 1, versionNonce: hash(`${id}:n`), isDeleted: false,
    boundElements: null, updated: NOW, link: null, locked: false,
    ...extra,
  }
}

const textWidth = (s: string, size: number) => Math.max(...s.split('\n').map(l => l.length)) * size * 0.55
const LINE = 1.25

function text(id: string, x: number, y: number, s: string, size: number, extra: El = {}): El {
  const lines = s.split('\n').length
  return base(id, 'text', x, y, textWidth(s, size), lines * size * LINE, {
    text: s, originalText: s, fontSize: size, fontFamily: 2, textAlign: 'left', verticalAlign: 'top',
    containerId: null, lineHeight: LINE, autoResize: true, strokeColor: '#0f172a', ...extra,
  })
}

/** Greedy wrap for long lines (title block). */
function wrap(s: string, max: number): string {
  const out: string[] = []; let line = ''
  for (const w of s.split(' ')) {
    if ((line + ' ' + w).trim().length > max) { out.push(line.trim()); line = w } else line += ' ' + w
  }
  if (line.trim()) out.push(line.trim())
  return out.join('\n')
}

export interface ExcalidrawScene {
  type: 'excalidraw'
  version: 2
  source: string
  elements: El[]
  appState: { viewBackgroundColor: string; gridSize: null }
  files: Record<string, never>
}

export function buildExcalidraw(r: Resolved, opts: { title?: string; date?: string; labels?: Partial<ExportLabels>; selectedNames?: string[] } = {}): ExcalidrawScene {
  const L = { ...DEFAULT_EXPORT_LABELS, ...opts.labels }
  const date = opts.date ?? new Date().toISOString().slice(0, 10)
  const els: El[] = []

  // title block
  const selected = (opts.selectedNames ?? r.selected).join(', ')
  els.push(text('title', 0, 0, opts.title ?? L.title, 28, { strokeColor: '#0f172a' }))
  els.push(text('subtitle', 0, 44, `${date}  |  ${L.edition}: ${L.editionValue}  |  ${L.generatedBy}`, 14, { strokeColor: '#475569' }))
  const selText = wrap(`${L.selected}: ${selected}`, 150)
  els.push(text('selected', 0, 70, selText, 14, { strokeColor: '#475569' }))
  const top = 70 + selText.split('\n').length * 14 * LINE + 40

  const lay = computeLayout(r, { top, left: 0 })

  // zones
  for (const z of lay.zones) {
    const id = `zone-${z.zone.id}`
    const idira = z.zone.id === 'idira-saas'
    els.push(base(id, 'rectangle', z.x, z.y, z.w, z.h, {
      strokeColor: idira ? '#1d4ed8' : z.zone.customer ? '#64748b' : '#94a3b8',
      backgroundColor: idira ? '#eff6ff' : z.zone.customer ? '#f8fafc' : 'transparent',
      strokeStyle: 'dashed', strokeWidth: 1, roundness: { type: 3 },
    }))
    els.push(text(`${id}-t`, z.x + 16, z.y + 14, z.zone.label.toUpperCase(), 14, { strokeColor: idira ? '#1d4ed8' : '#334155' }))
  }

  // nodes (rectangle + bound text)
  const bound: Record<string, Array<{ id: string; type: string }>> = {}
  for (const n of lay.nodes) {
    const id = `node-${n.node.id}`
    const c = PRODUCT_COLORS[n.node.product]
    const tid = `${id}-t`
    bound[id] = [{ id: tid, type: 'text' }]
    els.push(base(id, 'rectangle', n.x, n.y, n.w, n.h, {
      strokeColor: c.stroke, backgroundColor: c.bg, strokeWidth: 2, roundness: { type: 3 },
    }))
    const label = n.node.details ? `${n.node.label}\n${n.node.details}` : n.node.label
    const t = text(tid, n.x + 10, n.y + 10, label, 14, { containerId: id, textAlign: 'center', verticalAlign: 'middle' })
    t.width = n.w - 20
    t.y = n.y + (NODE_H - (t.height as number)) / 2
    els.push(t)
  }

  // arrows (bound to nodes) + bound label
  for (const e of lay.edges) {
    const st = DIRECTION_STYLE[e.direction]
    const sid = `node-${e.from}`, eid = `node-${e.to}`
    const dx = e.end.x - e.start.x, dy = e.end.y - e.start.y
    const lid = `${e.id}-t`
    els.push(base(e.id, 'arrow', e.start.x, e.start.y, Math.abs(dx), Math.abs(dy), {
      strokeColor: st.stroke, strokeStyle: st.style, strokeWidth: 2, roundness: { type: 2 },
      points: [[0, 0], [dx, dy]], lastCommittedPoint: null,
      startBinding: { elementId: sid, focus: 0, gap: 6 }, endBinding: { elementId: eid, focus: 0, gap: 6 },
      startArrowhead: null, endArrowhead: 'arrow', elbowed: false,
      boundElements: [{ id: lid, type: 'text' }],
    }))
    bound[sid]?.push({ id: e.id, type: 'arrow' })
    bound[eid]?.push({ id: e.id, type: 'arrow' })
    const lw = textWidth(e.label, 12)
    els.push(text(lid, e.start.x + dx / 2 - lw / 2, e.start.y + dy / 2 - 8, e.label, 12, {
      containerId: e.id, textAlign: 'center', verticalAlign: 'middle', strokeColor: st.stroke,
    }))
  }
  for (const el of els) if (bound[el.id as string]) el.boundElements = bound[el.id as string]

  // legend (below the diagram)
  const ly = top + lay.height + 50
  els.push(base('legend', 'rectangle', 0, ly, 520, 190, { strokeColor: '#94a3b8', roundness: { type: 3 } }))
  els.push(text('legend-t', 16, ly + 12, L.legend.toUpperCase(), 14, { strokeColor: '#334155' }))
  const rows: Array<[Direction, string]> = [['outbound', L.outbound], ['inbound', L.inbound], ['internal', L.internal], ['external', L.external]]
  rows.forEach(([d, label], i) => {
    const st = DIRECTION_STYLE[d]
    const y = ly + 48 + i * 28
    els.push(base(`legend-a-${d}`, 'arrow', 16, y + 8, 60, 0, {
      strokeColor: st.stroke, strokeStyle: st.style, strokeWidth: 2, roundness: { type: 2 },
      points: [[0, 0], [60, 0]], lastCommittedPoint: null, startBinding: null, endBinding: null,
      startArrowhead: null, endArrowhead: 'arrow', elbowed: false,
    }))
    els.push(text(`legend-l-${d}`, 90, y, label, 14))
  })
  els.push(text('legend-note', 0, ly + 210, wrap(L.inferredNote, 110), 12, { strokeColor: '#64748b' }))

  return { type: 'excalidraw', version: 2, source: 'https://demo.minha.cloud', elements: els, appState: { viewBackgroundColor: '#ffffff', gridSize: null }, files: {} }
}

// ---------------------------------------------------------------------------
// CSV and Markdown
// ---------------------------------------------------------------------------

const csvCell = (v: string) => (/[",\n;]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v)

export function toCsv(r: Resolved): string {
  const head = ['Source', 'Destination', 'Endpoint', 'Port', 'Protocol', 'Direction', 'Purpose', 'Required for', 'Edition', 'Confidence', 'Note', 'Source doc']
  const rows = r.flows.map(f => [
    nodeById(f.from).label, nodeById(f.to).label, f.endpoint, f.port, f.protocol, f.direction, f.purpose,
    f.requiredFor.filter(t => r.selected.includes(t)).join(' '), f.edition, f.confidence, f.note ?? '', f.source.url,
  ])
  return [head, ...rows].map(row => row.map(csvCell).join(',')).join('\n') + '\n'
}

const md = (s: string) => s.replace(/\|/g, '\\|')

export function toMarkdown(r: Resolved, opts: { title?: string; date?: string; labels?: Partial<ExportLabels>; selectedNames?: string[] } = {}): string {
  const L = { ...DEFAULT_EXPORT_LABELS, ...opts.labels }
  const date = opts.date ?? new Date().toISOString().slice(0, 10)
  const out: string[] = []
  out.push(`# ${opts.title ?? L.title}`, '', `${date} | ${L.edition}: ${L.editionValue} | ${L.generatedBy}`, '')
  out.push('## Environment', '', ...(opts.selectedNames ?? r.selected).map(s => `- ${s}`), '')

  out.push('## Components and requirements', '')
  const byNode = new Map<string, typeof r.requirements>()
  r.requirements.forEach(q => byNode.set(q.node, [...(byNode.get(q.node) ?? []), q]))
  for (const [nid, reqs] of byNode) {
    out.push(`### ${nodeById(nid).label}`, '')
    reqs.forEach(q => out.push(`- [ ] ${q.text} (${q.category}, ${q.confidence}${q.note ? `: ${q.note}` : ''}) [doc](${q.source.url})`))
    out.push('')
  }

  out.push('## Network flows', '', '| Source | Destination | Endpoint | Port | Protocol | Direction | Purpose | Confidence |', '|---|---|---|---|---|---|---|---|')
  r.flows.forEach(f => out.push(`| ${md(nodeById(f.from).label)} | ${md(nodeById(f.to).label)} | \`${md(f.endpoint)}\` | ${f.port} | ${md(f.protocol)} | ${f.direction} | ${md(f.purpose)} | ${f.confidence} |`))
  out.push('')

  out.push('## Consolidated firewall rules', '')
  for (const g of r.firewallRules) {
    out.push(`### ${g.direction.toUpperCase()}: from ${g.sourceLabel}`, '')
    g.rules.forEach(rule => out.push(`- [ ] ${rule.protocol} ${rule.port} to \`${rule.endpoint}\` (${rule.destination}): ${rule.purpose}${rule.confidence === 'inferred' ? ' [inferred]' : ''}`))
    out.push('')
  }

  const inferred = r.flows.filter(f => f.confidence === 'inferred')
  out.push('## Notes', '', `- ${L.inferredNote}`)
  inferred.forEach(f => f.note && out.push(`- ${nodeById(f.from).label} to ${nodeById(f.to).label}: ${f.note}`))
  out.push('')

  const docs = new Map<string, string>()
  r.flows.forEach(f => docs.set(f.source.url, f.source.path))
  r.requirements.forEach(q => docs.set(q.source.url, q.source.path))
  out.push('## Documentation', '', ...[...docs.keys()].sort().map(u => `- ${u}`), '')
  return out.join('\n')
}
