/**
 * Shared export pieces (labels, palette, flow numbering) plus the CSV and
 * Markdown exports of a resolved selection. The draw.io diagram lives in
 * drawio.ts. Colours here are hex on purpose: the files are opened outside
 * the site.
 */
import { computeLayout } from './layout'
import type { Direction, Product, Resolved } from './netCatalog'
import { nodeById } from './netCatalog'

export interface ExportLabels {
  title: string
  generatedBy: string          // "Generated by Machine Identity Academy (demo.minha.cloud)"
  selected: string             // "Selected"
  goals: string                // "Goals"
  edition: string              // "Edition"
  editionValue: string         // "SaaS" | "Self-Hosted"
  legend: string
  outbound: string
  inbound: string
  internal: string
  external: string
  badgeDocumented: string      // legend: filled badge
  badgeInferred: string        // legend: hollow badge
  tableNote: string            // "Numbers match the network flows table"
  inferredNote: string         // footnote on inferred flows
  products: string             // legend: product colours title
  zones?: Record<string, string>
  // table / document headings
  number: string
  source: string
  destination: string
  endpoint: string
  port: string
  protocol: string
  direction: string
  purpose: string
  confidence: string
  documented: string
  inferred: string
  requiredFor: string
  doc: string
  environment: string
  components: string
  flows: string
  rules: string
  notes: string
  documentation: string
  from: string
  directions: Record<Direction, string>
}

export const DEFAULT_EXPORT_LABELS: ExportLabels = {
  title: 'Reference architecture',
  generatedBy: 'Generated by Machine Identity Academy (demo.minha.cloud)',
  selected: 'Selected',
  goals: 'Goals',
  edition: 'Edition',
  editionValue: 'SaaS',
  legend: 'Legend',
  outbound: 'Outbound from the customer network',
  inbound: 'Inbound to the customer network',
  internal: 'Inside the customer network',
  external: 'Between providers (no customer rule)',
  badgeDocumented: 'Connection number: port and endpoint documented',
  badgeInferred: 'Connection number: inferred, confirm before opening rules',
  tableNote: 'Each number refers to a row of the network flows table (source, destination, endpoint, port, protocol, purpose and documentation link).',
  inferredNote: 'Inferred flows follow the documentation but the port or endpoint is not spelled out there: confirm them before opening firewall rules.',
  products: 'Products',
  number: 'No.',
  source: 'Source',
  destination: 'Destination',
  endpoint: 'Endpoint',
  port: 'Port',
  protocol: 'Protocol',
  direction: 'Direction',
  purpose: 'Purpose',
  confidence: 'Confidence',
  documented: 'documented',
  inferred: 'inferred',
  requiredFor: 'Required for',
  doc: 'Doc',
  environment: 'Environment',
  components: 'Components and requirements',
  flows: 'Network flows',
  rules: 'Consolidated firewall rules',
  notes: 'Notes',
  documentation: 'Documentation',
  from: 'from',
  directions: { outbound: 'Outbound', inbound: 'Inbound', internal: 'Internal', external: 'Between providers' },
}

export const PRODUCT_COLORS: Record<Product, { stroke: string; bg: string }> = {
  sm: { stroke: '#0058E6', bg: '#E8F0FD' },
  swa: { stroke: '#0E7490', bg: '#E2F3F7' },
  cp: { stroke: '#6048D6', bg: '#EFECFB' },
  shub: { stroke: '#BE185D', bg: '#FBE8F1' },
  customer: { stroke: '#475569', bg: '#f1f5f9' },
  external: { stroke: '#334155', bg: '#ffffff' },
}

/** Line colour / style per direction, and the badge colour (darker for the light grey lines). */
export const DIRECTION_STYLE: Record<Direction, { stroke: string; style: 'solid' | 'dashed' | 'dotted'; badge: string }> = {
  outbound: { stroke: '#0058E6', style: 'solid', badge: '#0058E6' },
  inbound: { stroke: '#DC2626', style: 'solid', badge: '#DC2626' },
  internal: { stroke: '#475569', style: 'dashed', badge: '#475569' },
  external: { stroke: '#94A3B8', style: 'dotted', badge: '#64748B' },
}

/** Flows with the number of the diagram edge they are drawn on, in number order. */
export function numberedFlows(r: Resolved) {
  const { flowNo } = computeLayout(r)
  return r.flows
    .map(f => ({ ...f, no: flowNo[f.id] ?? 0 }))
    .sort((a, b) => (a.no || 1e9) - (b.no || 1e9))
}

// ---------------------------------------------------------------------------
// CSV and Markdown
// ---------------------------------------------------------------------------

const csvCell = (v: string) => (/[",\n;]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v)

export function toCsv(r: Resolved, opts: { labels?: Partial<ExportLabels> } = {}): string {
  const L = { ...DEFAULT_EXPORT_LABELS, ...opts.labels }
  const head = [L.number, L.source, L.destination, L.endpoint, L.port, L.protocol, L.direction, L.purpose, L.edition, L.confidence, L.notes, L.doc]
  const rows = numberedFlows(r).map(f => [
    f.no ? String(f.no) : '', nodeById(f.from).label, nodeById(f.to).label, f.endpoint, f.port, f.protocol, L.directions[f.direction], f.purpose,
    f.edition === 'both' ? 'SaaS, Self-Hosted' : f.edition === 'saas' ? 'SaaS' : 'Self-Hosted', f.confidence === 'documented' ? L.documented : L.inferred, f.note ?? '', f.source.url,
  ])
  // BOM so spreadsheet apps open accents correctly
  return '﻿' + [head, ...rows].map(row => row.map(csvCell).join(',')).join('\n') + '\n'
}

const md = (s: string) => s.replace(/\|/g, '\\|')

export function toMarkdown(r: Resolved, opts: { title?: string; date?: string; labels?: Partial<ExportLabels>; selectedNames?: string[]; goalNames?: string[] } = {}): string {
  const L = { ...DEFAULT_EXPORT_LABELS, ...opts.labels }
  const date = opts.date ?? new Date().toISOString().slice(0, 10)
  const out: string[] = []
  out.push(`# ${opts.title ?? L.title}`, '', `${date} | ${L.edition}: ${L.editionValue}`, '', `_${L.generatedBy}_`, '')
  out.push(`## ${L.environment}`, '', ...(opts.selectedNames ?? r.selected).map(s => `- ${s}`), '')
  if (opts.goalNames?.length) out.push(`**${L.goals}:** ${opts.goalNames.join(', ')}`, '')

  out.push(`## ${L.components}`, '')
  const byNode = new Map<string, typeof r.requirements>()
  r.requirements.forEach(q => byNode.set(q.node, [...(byNode.get(q.node) ?? []), q]))
  for (const [nid, reqs] of byNode) {
    out.push(`### ${nodeById(nid).label}`, '')
    reqs.forEach(q => out.push(`- [ ] ${q.text}${q.confidence === 'inferred' ? ` (${L.inferred}${q.note ? `: ${q.note}` : ''})` : ''} [${L.doc}](${q.source.url})`))
    out.push('')
  }

  out.push(`## ${L.flows}`, '', L.tableNote, '',
    `| ${L.number} | ${L.source} | ${L.destination} | ${L.endpoint} | ${L.port} | ${L.protocol} | ${L.direction} | ${L.purpose} | ${L.confidence} |`,
    '|---|---|---|---|---|---|---|---|---|')
  numberedFlows(r).forEach(f => out.push(`| ${f.no || ''} | ${md(nodeById(f.from).label)} | ${md(nodeById(f.to).label)} | \`${md(f.endpoint)}\` | ${f.port} | ${md(f.protocol)} | ${L.directions[f.direction]} | ${md(f.purpose)} | ${f.confidence === 'documented' ? L.documented : L.inferred} |`))
  out.push('')

  out.push(`## ${L.rules}`, '')
  for (const g of r.firewallRules) {
    out.push(`### ${L.directions[g.direction]}: ${L.from} ${L.zones?.[g.sourceZone] ?? g.sourceLabel}`, '')
    g.rules.forEach(rule => out.push(`- [ ] ${rule.protocol} ${rule.port} → \`${rule.endpoint}\` (${rule.destination}): ${rule.purpose}${rule.confidence === 'inferred' ? ` [${L.inferred}]` : ''}`))
    out.push('')
  }

  const inferred = r.flows.filter(f => f.confidence === 'inferred' && f.note)
  out.push(`## ${L.notes}`, '', `- ${L.inferredNote}`)
  const seen = new Set<string>()
  inferred.forEach(f => { if (!seen.has(f.note!)) { seen.add(f.note!); out.push(`- ${nodeById(f.from).label} → ${nodeById(f.to).label}: ${f.note}`) } })
  out.push('')

  const docs = new Set<string>()
  r.flows.forEach(f => docs.add(f.source.url))
  r.requirements.forEach(q => docs.add(q.source.url))
  out.push(`## ${L.documentation}`, '', ...[...docs].sort().map(u => `- ${u}`), '')
  return out.join('\n')
}
