/**
 * Shared export pieces (labels, palette) plus the CSV and Markdown exports of
 * a resolved selection. The draw.io diagram lives in drawio.ts.
 * Colours here are hex on purpose: the files are opened outside the site.
 */
import type { Direction, Product, Resolved } from './netCatalog'
import { nodeById } from './netCatalog'

export interface ExportLabels {
  title: string
  generatedBy: string          // "Generated by Machine Identity Academy (demo.minha.cloud)"
  selected: string             // "Selected"
  edition: string              // "Edition"
  editionValue: string         // "SaaS" | "Self-Hosted"
  legend: string
  outbound: string
  inbound: string
  internal: string
  external: string
  inferredNote: string         // footnote on inferred flows
  documented: string           // legend: solid line
  inferred: string             // legend: dashed line + asterisk
  products: string             // legend: product colours title
}

export const DEFAULT_EXPORT_LABELS: ExportLabels = {
  title: 'Reference architecture',
  generatedBy: 'Generated by Machine Identity Academy (demo.minha.cloud)',
  selected: 'Selected',
  edition: 'Edition',
  editionValue: 'SaaS',
  legend: 'Legend',
  outbound: 'Outbound from customer network',
  inbound: 'Inbound to customer network',
  internal: 'Internal (customer network)',
  external: 'Provider to provider (no customer rule)',
  inferredNote: 'Flows marked "inferred" follow the docs but the port or endpoint is not spelled out there: confirm before opening firewall rules.',
  documented: 'Documented port or endpoint',
  inferred: 'Inferred (*): confirm before opening rules',
  products: 'Products',
}

export const PRODUCT_COLORS: Record<Product, { stroke: string; bg: string }> = {
  sm: { stroke: '#0058E6', bg: '#E8F0FD' },
  swa: { stroke: '#0E7490', bg: '#E2F3F7' },
  cp: { stroke: '#6048D6', bg: '#EFECFB' },
  shub: { stroke: '#BE185D', bg: '#FBE8F1' },
  customer: { stroke: '#475569', bg: '#f1f5f9' },
  external: { stroke: '#334155', bg: '#ffffff' },
}

export const DIRECTION_STYLE: Record<Direction, { stroke: string; style: 'solid' | 'dashed' | 'dotted' }> = {
  outbound: { stroke: '#0058E6', style: 'solid' },
  inbound: { stroke: '#dc2626', style: 'solid' },
  internal: { stroke: '#475569', style: 'dashed' },
  external: { stroke: '#94a3b8', style: 'dotted' },
}

// ---------------------------------------------------------------------------
// CSV and Markdown
// ---------------------------------------------------------------------------

const csvCell = (v: string) => (/[",\n;]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v)

export function toCsv(r: Resolved): string {
  const head = ['Source', 'Destination', 'Endpoint', 'Port', 'Protocol', 'Direction', 'Purpose', 'Required for', 'Edition', 'Confidence', 'Note', 'Source doc']
  const rows = r.flows.map(f => [
    nodeById(f.from).label, nodeById(f.to).label, f.endpoint, f.port, f.protocol, f.direction, f.purpose,
    f.requiredFor.filter(t => r.selected.includes(t)).join(' '), f.edition, f.confidence, f.note ?? '', f.source.url,
  ])
  return [head, ...rows].map(row => row.map(csvCell).join(',')).join('\n') + '\n'
}

const md = (s: string) => s.replace(/\|/g, '\\|')

export function toMarkdown(r: Resolved, opts: { title?: string; date?: string; labels?: Partial<ExportLabels>; selectedNames?: string[] } = {}): string {
  const L = { ...DEFAULT_EXPORT_LABELS, ...opts.labels }
  const date = opts.date ?? new Date().toISOString().slice(0, 10)
  const out: string[] = []
  out.push(`# ${opts.title ?? L.title}`, '', `${date} | ${L.edition}: ${L.editionValue} | ${L.generatedBy}`, '')
  out.push('## Environment', '', ...(opts.selectedNames ?? r.selected).map(s => `- ${s}`), '')

  out.push('## Components and requirements', '')
  const byNode = new Map<string, typeof r.requirements>()
  r.requirements.forEach(q => byNode.set(q.node, [...(byNode.get(q.node) ?? []), q]))
  for (const [nid, reqs] of byNode) {
    out.push(`### ${nodeById(nid).label}`, '')
    reqs.forEach(q => out.push(`- [ ] ${q.text} (${q.category}, ${q.confidence}${q.note ? `: ${q.note}` : ''}) [doc](${q.source.url})`))
    out.push('')
  }

  out.push('## Network flows', '', '| Source | Destination | Endpoint | Port | Protocol | Direction | Purpose | Confidence |', '|---|---|---|---|---|---|---|---|')
  r.flows.forEach(f => out.push(`| ${md(nodeById(f.from).label)} | ${md(nodeById(f.to).label)} | \`${md(f.endpoint)}\` | ${f.port} | ${md(f.protocol)} | ${f.direction} | ${md(f.purpose)} | ${f.confidence} |`))
  out.push('')

  out.push('## Consolidated firewall rules', '')
  for (const g of r.firewallRules) {
    out.push(`### ${g.direction.toUpperCase()}: from ${g.sourceLabel}`, '')
    g.rules.forEach(rule => out.push(`- [ ] ${rule.protocol} ${rule.port} to \`${rule.endpoint}\` (${rule.destination}): ${rule.purpose}${rule.confidence === 'inferred' ? ' [inferred]' : ''}`))
    out.push('')
  }

  const inferred = r.flows.filter(f => f.confidence === 'inferred')
  out.push('## Notes', '', `- ${L.inferredNote}`)
  inferred.forEach(f => f.note && out.push(`- ${nodeById(f.from).label} to ${nodeById(f.to).label}: ${f.note}`))
  out.push('')

  const docs = new Map<string, string>()
  r.flows.forEach(f => docs.set(f.source.url, f.source.path))
  r.requirements.forEach(q => docs.set(q.source.url, q.source.path))
  out.push('## Documentation', '', ...[...docs.keys()].sort().map(u => `- ${u}`), '')
  return out.join('\n')
}
